minimum_pre_commit_version: "3.5.0"

# Exclude ephemeral files that cause recurring formatting issues
exclude: ^attached_assets/

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Black removed in favor of Ruff formatter

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.32
    hooks:
      - id: pymarkdown
        name: pymarkdown-lint
        args: [
          "--config=.pymarkdown.json",
          "scan",
          "README.md",
          "CODE_OF_CONDUCT.md",
          "CONTRIBUTING.md",
          "docs",
          "tests/README.md"
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml", "--python-version=3.12"]
        additional_dependencies:
          ["pydantic>=2.7.0", "types-requests", "types-setuptools"]
